<a href="https://colab.research.google.com/github/abhiraj7821/AIML-Projects/blob/main/Kaggle%20Compititions/Titanic_Machine_Learning_from_Disaster_Proj.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Kaggle-Titanic - Machine Learning from Disaster

In [178]:
#Importing required
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
#EDA-Ecploratory Data Analysis
#Load the Dataset
titanic_train_df=pd.read_csv('/content/train.csv')
titanic_test_df=pd.read_csv('/content/test.csv')
print("Shape of titanic_train_df",titanic_train_df.shape)
print("Shape of titanic_test_df",titanic_test_df.shape)

Shape of titanic_train_df (891, 12)
Shape of titanic_test_df (418, 11)


In [179]:
titanic_train_df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [180]:
titanic_train_df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [181]:
titanic_test_df.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [182]:
titanic_train_df['Age'].fillna(titanic_train_df['Age'].mean(),inplace=True)

In [183]:
titanic_test_df['Age'].fillna(titanic_test_df['Age'].mean(),inplace=True)
titanic_test_df['Fare'].fillna(titanic_test_df['Fare'].mean(),inplace=True)

In [184]:
print("Shape of titanic_train_df",titanic_train_df.shape)
print("Shape of titanic_test_df",titanic_test_df.shape)

Shape of titanic_train_df (891, 12)
Shape of titanic_test_df (418, 11)


In [185]:
titanic_train_df.isnull().sum()
titanic_test_df.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          327
Embarked         0
dtype: int64

In [186]:
titanic_train_df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [187]:
#prepare X_train,y_train,X_test,y_test
#Feature Engneering
#Converted 'Sex', 'Embarked', and 'Title' into numbers using one-hot encoding.
#Sex
titanic_train_df['Sex'] = titanic_train_df['Sex'].str.lower().str.strip().map({'male': 0, 'female': 1})
titanic_test_df['Sex'] = titanic_test_df['Sex'].str.lower().str.strip().map({'male': 0, 'female':1})
#Embarked
titanic_train_df['Embarked'] = titanic_train_df['Embarked'].str.lower().str.strip().map({'c': 0, 'q': 1,'s':2})
titanic_test_df['Embarked'] = titanic_test_df['Embarked'].str.lower().str.strip().map({'c': 0, 'q': 1,'s':2})
#handining nan values
titanic_train_df['Embarked'].fillna(titanic_train_df['Embarked'].mean(),inplace=True)
#Title

#Adding new column 'Family Size' by combining SibSp and Parch for both train and test df
titanic_train_df['Family_size']=titanic_train_df['SibSp']+titanic_train_df['Parch']
titanic_test_df['Family_size']=titanic_test_df['SibSp']+titanic_test_df['Parch']

In [188]:
titanic_train_df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    0  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.0      1      0   
2                             Heikkinen, Miss. Laina    1  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.0      1      0   
4                           Allen, Mr. William Henry    0  35.0      0      0   

             Ticket     Fare Cabin  Embarked  Family_size  
0         A/5 21171   7.2500   NaN       2.0            1  
1          PC 17599  71.2833   C85       0.0            1  
2  STON/O2. 3101282   7.9250   NaN       2.0            0  
3            113803  53.1000  C123       2.0            1  
4            373450   8.0500   NaN       2.0            0

In [189]:
# prompt: Adding isALone column for finding is the pasenger traveling alone as 1 and if not alone then 0

# Adding 'isAlone' column
titanic_train_df['isAlone'] = 0
titanic_train_df.loc[titanic_train_df['Family_size'] == 0, 'isAlone'] = 1

titanic_test_df['isAlone'] = 0
titanic_test_df.loc[titanic_test_df['Family_size'] == 0, 'isAlone'] = 1


In [190]:
titanic_train_df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    0  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.0      1      0   
2                             Heikkinen, Miss. Laina    1  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.0      1      0   
4                           Allen, Mr. William Henry    0  35.0      0      0   

             Ticket     Fare Cabin  Embarked  Family_size  isAlone  
0         A/5 21171   7.2500   NaN       2.0            1        0  
1          PC 17599  71.2833   C85       0.0            1        0  
2  STON/O2. 3101282   7.9250   NaN       2.0            0        1  
3            113803  53.1000  C123       2.0            1        0  
4            373450   8.0500   NaN       2.0            0        1

In [191]:
print("Shape of titanic_train_df",titanic_train_df.shape)
print("Shape of titanic_test_df",titanic_test_df.shape)

Shape of titanic_train_df (891, 14)
Shape of titanic_test_df (418, 13)


In [192]:
#Defining X_train,y_train
X_train=titanic_train_df[['Pclass','Sex','Age','SibSp','Parch','Fare','Embarked','Family_size','isAlone']]
y_train=titanic_train_df['Survived']

In [193]:
X_train.shape

(891, 9)

In [194]:
y_train.shape

(891,)

In [195]:
#Defining y_test
X_test=titanic_test_df[['Pclass','Sex','Age','SibSp','Parch','Fare','Embarked','Family_size','isAlone']]
X_test.shape

(418, 9)

In [196]:
# Model Preperation
from sklearn.linear_model import LinearRegression
model=LinearRegression()
#train the model
model.fit(X_train,y_train)
#test the model
y_pred=model.predict(X_test)
y_pred

array([ 8.98427407e-02,  5.19946301e-01,  9.62742118e-02,  1.00760417e-01,
        6.22146075e-01,  1.73507771e-01,  6.09136704e-01,  2.69846372e-01,
        7.07221705e-01,  1.16716753e-01,  8.22669175e-02,  3.18555985e-01,
        9.94535073e-01,  1.01304513e-01,  8.54449931e-01,  8.76179493e-01,
        2.47795730e-01,  1.96244072e-01,  6.31882497e-01,  5.56466706e-01,
        3.77441636e-01,  2.56995488e-01,  9.02234339e-01,  5.88057777e-01,
        8.52544485e-01,  1.11324974e-02,  1.07687331e+00,  1.87868862e-01,
        3.47770925e-01,  1.26628351e-01,  1.73889670e-01,  2.61526855e-01,
        5.24205845e-01,  5.40263269e-01,  5.16552701e-01,  2.10203967e-01,
        5.76537382e-01,  6.28487260e-01,  1.12168857e-01,  9.62806871e-02,
        1.54842991e-01,  4.06528155e-01,  2.23575021e-02,  7.38927869e-01,
        8.63131078e-01,  1.11714707e-01,  3.87603666e-01,  1.13423534e-01,
        8.11512241e-01,  5.65226441e-01,  4.88305014e-01,  3.24435904e-01,
        7.36724070e-01,  

In [197]:
y_pred_df=pd.DataFrame(y_pred)
y_pred_df = (y_pred_df >= 0.6).astype(int)
test_PassengerIds=titanic_test_df['PassengerId']

In [198]:
# Ensure both are 1D Series
y_pred_df = y_pred_df.squeeze().reset_index(drop=True)
test_PassengerIds = test_PassengerIds.squeeze().reset_index(drop=True)

# Combine into a DataFrame
gender_submission_Final_pridiction = pd.DataFrame({
    'PassengerId': test_PassengerIds,
    'Survived': y_pred_df
})


gender_submission_Final_pridiction

PassengerId  Survived
0            892         0
1            893         0
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [199]:

gender_submission_Final_pridiction.to_csv('gender_submission_Final_pridiction.csv', index=False)


####using polinomial regression for prediction

In [200]:
#using polinomial regression for prediction
from sklearn.preprocessing import PolynomialFeatures
poly=PolynomialFeatures(degree=2)

model=LinearRegression()
X_poly=poly.fit_transform(X_train)
X_test_poly=poly.fit_transform(X_test)
model.fit(X_poly,y_train)
poly_predict=model.predict(X_test_poly)
poly_predict

array([ 0.11549111,  0.41500293,  0.04428734,  0.0969411 ,  0.45411697,
        0.1730168 ,  0.65423208,  0.35955658,  0.67425133,  0.04643317,
        0.07884562,  0.26661335,  1.01240535, -0.02389033,  1.01792003,
        0.85163862,  0.16241178,  0.21695975,  0.45587404,  0.66585417,
        0.23744151,  0.52842364,  1.09955543,  0.56539131,  0.66756666,
       -0.04474279,  1.03971438,  0.20363269,  0.28313518,  0.20390016,
        0.03964124,  0.25032003,  0.36186748,  0.39206085,  0.48522521,
        0.24019116,  0.60731929,  0.59241014,  0.11094273,  0.40546666,
        0.08497139,  0.34855562,  0.04942623,  0.79096145,  1.01058774,
        0.1017393 ,  0.26386658,  0.13625801,  1.15144048,  0.40042738,
        0.46092283,  0.23441711,  0.81795949,  0.79941257,  0.2052818 ,
        0.1998484 ,  0.06319848,  0.10013553,  0.10373664,  0.89155071,
        0.14666297,  0.1344516 ,  0.13958909,  0.65232237,  0.43161909,
        0.80405223,  0.65656833,  0.25851841,  0.38196965,  0.55

In [201]:
poly_predict.shape

(418,)

In [202]:
poly_predict=pd.DataFrame(poly_predict)
poly_predict = (poly_predict >= 0.6).astype(int)
test_PassengerIds=titanic_test_df['PassengerId']

In [203]:
# Ensure both are 1D Series
poly_predict = poly_predict.squeeze().reset_index(drop=True)
test_PassengerIds = test_PassengerIds.squeeze().reset_index(drop=True)

# Combine into a DataFrame
gender_submission_Final_pridiction_using_polynomial_regression = pd.DataFrame({
    'PassengerId': test_PassengerIds,
    'Survived': poly_predict
})


gender_submission_Final_pridiction_using_polynomial_regression

PassengerId  Survived
0            892         0
1            893         0
2            894         0
3            895         0
4            896         0
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [204]:

gender_submission_Final_pridiction_using_polynomial_regression.to_csv('gender_submission_Final_pridiction_using_polynomial_regression.csv', index=False)


###Using SVM Predicting Titanic Prediction

In [205]:
from sklearn.svm import SVC
model=SVC(kernel='rbf')
model.fit(X_train,y_train)

y_pred_usingSVM=model.predict(X_test)
y_pred_usingSVM

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,

In [206]:
# Ensure both are 1D Series
y_pred_usingSVM = y_pred_df.squeeze().reset_index(drop=True)
test_PassengerIds = test_PassengerIds.squeeze().reset_index(drop=True)

# Combine into a DataFrame
gender_submission_Final_pridiction_using_SVM = pd.DataFrame({
    'PassengerId': test_PassengerIds,
    'Survived': y_pred_usingSVM
})
gender_submission_Final_pridiction_using_SVM

PassengerId  Survived
0            892         0
1            893         0
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [207]:
# prompt: find number of unique values bitween gender_submission_Final_pridiction_using_SVM and gender_submission_Final_pridiction_using_polynomial_regression using pandas

# Assuming the code you provided is in a Jupyter Notebook cell and has been executed.
# The following code calculates the number of unique values in the 'Survived' column for both dataframes.

import pandas as pd

# Assuming gender_submission_Final_pridiction_using_SVM and
# gender_submission_Final_pridiction_using_polynomial_regression are already defined from your previous code.

# Find unique values in 'Survived' column of each dataframe
unique_svm = gender_submission_Final_pridiction_using_SVM['Survived'].unique()
unique_poly = gender_submission_Final_pridiction_using_polynomial_regression['Survived'].unique()

# Combine unique values and find the total number of unique values
all_unique = pd.concat([pd.Series(unique_svm), pd.Series(unique_poly)]).unique()

num_unique = len(all_unique)
print("Number of unique values between the two dataframes:", num_unique)


Number of unique values between the two dataframes: 2


In [208]:
gender_submission_Final_pridiction_using_SVM.to_csv('SVM_gender_submission_Final_pridiction_using_SVM.csv', index=False)

###Using Random Forest for prediction

In [209]:
from sklearn.ensemble import RandomForestClassifier
#Initialize Random Forest CLassifer
rf_classifier=RandomForestClassifier(n_estimators=100,random_state=42)
#fit
rf_classifier.fit(X_train,y_train)
#predict
y_pred_using_rf=rf_classifier.predict(X_test)
y_pred_using_rf

array([0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [210]:
# Ensure both are 1D Series
y_pred_using_rf = pd.DataFrame(y_pred_using_rf).squeeze().reset_index(drop=True)
test_PassengerIds = test_PassengerIds.squeeze().reset_index(drop=True)

# Combine into a DataFrame
gender_submission_Final_pridiction_using_rf = pd.DataFrame({
    'PassengerId': test_PassengerIds,
    'Survived': y_pred_using_rf
})
gender_submission_Final_pridiction_using_rf

PassengerId  Survived
0            892         0
1            893         0
2            894         0
3            895         1
4            896         0
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         1

[418 rows x 2 columns]

In [211]:
gender_submission_Final_pridiction_using_rf.to_csv('rf_gender_submission_Final_pridiction_using_rf.csv', index=False)